In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
ids_df = pd.read_csv('IDSdataset2.csv')

In [3]:
ids_df.head

ids_df.describe()

#to check for missing values
ids_df.isna().sum()

MI_dir_L0.1_weight      0
MI_dir_L0.1_mean        0
MI_dir_L0.1_variance    0
H_L0.1_weight           0
H_L0.1_mean             0
H_L0.1_variance         0
HH_L0.1_weight          0
HH_L0.1_mean            0
HH_L0.1_std             0
HH_L0.1_magnitude       0
HH_L0.1_radius          0
HH_L0.1_covariance      0
HH_L0.1_pcc             0
HH_jit_L0.1_weight      0
HH_jit_L0.1_mean        0
HH_jit_L0.1_variance    0
HpHp_L0.1_weight        0
HpHp_L0.1_mean          0
HpHp_L0.1_std           0
HpHp_L0.1_magnitude     0
HpHp_L0.1_radius        0
HpHp_L0.1_covariance    0
HpHp_L0.1_pcc           0
Device_Name             0
Attack                  0
Attack_subType          0
label                   0
dtype: int64

In [4]:
#to get unique elements in the column
print(ids_df['Device_Name'].unique())

['Danmini_Doorbell' 'Ecobee_Thermostat' 'Ennio_Doorbell'
 'Philips_B120N10_Baby_Monitor' 'Provision_PT_737E_Security_Camera'
 'Provision_PT_838_Security_Camera' 'Samsung_SNH_1011_N_Webcam'
 'SimpleHome_XCS7_1002_WHT_Security_Camera'
 'SimpleHome_XCS7_1003_WHT_Security_Camera']

In [5]:
#since there are categorical variables, convert categorical variables to numerical
from sklearn.preprocessing import OneHotEncoder
ids_df['Device_Name'] = ids_df['Device_Name'].astype('category')
ids_df['Attack'] = ids_df['Attack'].astype('category')
ids_df['Attack_subType'] = ids_df['Attack_subType'].astype('category')

ids_df['Device_Name'] = ids_df['Device_Name'].cat.codes
ids_df['Attack'] = ids_df['Attack'].cat.codes
ids_df['Attack_subType'] = ids_df['Attack_subType'].cat.codes

enc = OneHotEncoder(sparse_output=False)

enc_data = pd.DataFrame(enc.fit_transform(
    ids_df[['Device_Name','Attack','Attack_subType']]))

ids_df = ids_df.join(enc_data)

In [6]:
ids_df

,MI_dir_L0.1_weight,MI_dir_L0.1_mean,MI_dir_L0.1_variance,H_L0.1_weight,H_L0.1_mean,H_L0.1_variance,HH_L0.1_weight,HH_L0.1_mean,HH_L0.1_std,HH_L0.1_magnitude,...,11,12,13,14,15,16,17,18,19,20
0,1.000000,98.000000,0.000000e+00,1.000000,98.000000,0.000000e+00,1.000000,98.000000,0.000000e+00,98.000000,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
1,1.931640,98.000000,1.818989e-12,1.931640,98.000000,1.818989e-12,1.931640,98.000000,1.348699e-06,138.592929,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2.904273,86.981750,2.311822e+02,2.904273,86.981750,2.311822e+02,1.000000,66.000000,0.000000e+00,114.856432,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
3,3.902546,83.655268,2.040614e+02,3.902546,83.655268,2.040614e+02,1.000000,74.000000,0.000000e+00,74.000000,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
4,4.902545,81.685828,1.775746e+02,4.902545,81.685828,1.775746e+02,2.000000,74.000000,9.536743e-07,74.000000,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7062601,2.937269,217.763487,1.770682e+04,2.937269,217.763487,1.770682e+04,1.220882,60.000000,9.540000e-07,84.852814,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7062602,1.730254,282.630543,1.054589e+04,1.730254,282.630543,1.054589e+04,1.213342,330.000000,5.390000e-06,431.490440,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7062603,2.730251,299.980395,7.204117e+03,2.730251,299.980395,7.204117e+03,1.213352,330.000000,6.610000e-06,431.490440,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7062604,2.882414,216.723647,1.775308e+04,2.882414,216.723647,1.775308e+04,1.209274,60.000000,6.740000e-07,84.852814,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7062605,2.032574,154.377267,1.303249e+04,2.032574,154.377267,1.303249e+04,1.299681,145.339354,1.010891e+02,195.783485,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [7]:
X = ids_df.drop(columns='label')
y = ids_df['label']

In [8]:
X.columns = X.columns.astype(str)

In [9]:
from sklearn.model_selection import train_test_split
X_train, X_test,y_train,y_test = train_test_split(X,y,test_size=0.2)

In [10]:
X_test.shape
X_test

,MI_dir_L0.1_weight,MI_dir_L0.1_mean,MI_dir_L0.1_variance,H_L0.1_weight,H_L0.1_mean,H_L0.1_variance,HH_L0.1_weight,HH_L0.1_mean,HH_L0.1_std,HH_L0.1_magnitude,...,11,12,13,14,15,16,17,18,19,20
3917054,1.000000,60.000000,0.000000,1.000000,60.000000,0.000000,1.000000,60.000000,0.000000,60.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
138691,1.000000,60.000000,0.000000,1.000000,60.000000,0.000000,1.000000,60.000000,0.000000,60.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
5914720,1.000000,60.000000,0.000000,1.000000,60.000000,0.000000,1.000000,60.000000,0.000000,60.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
761351,6368.983360,381.558514,55444.768757,6368.983360,381.558514,55444.768757,4146.123980,553.937774,5.543996,553.937774,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
6131828,1902.267339,60.121201,2.428445,1902.267339,60.121201,2.428445,1.000000,60.000000,0.000000,60.000000,...,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6226214,6741.355937,70.604437,36.007654,6741.355937,70.604437,36.007654,5103.472197,73.998996,0.118567,73.998996,...,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
1944055,1.000000,60.000000,0.000000,1.000000,60.000000,0.000000,1.000000,60.000000,0.000000,60.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
1233722,1.000000,60.000000,0.000000,1.000000,60.000000,0.000000,1.000000,60.000000,0.000000,60.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3319751,1.000000,60.000000,0.000000,1.000000,60.000000,0.000000,1.000000,60.000000,0.000000,60.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3021372,5027.153369,337.170231,60093.068127,5027.153369,337.170231,60093.068127,1.000000,60.000000,0.000000,60.000000,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [11]:
X_train.shape

(5650084, 47)

In [12]:
y_train.shape

(5650084,)

In [13]:
from sklearn.neighbors import KNeighborsClassifier
k=4
neigh = KNeighborsClassifier(n_neighbors=k)

In [14]:
neigh = neigh.fit(X_train,y_train)

In [ ]:
y_pred = neigh.predict(X_test)

In [ ]:
from sklearn import metrics
print("Train set accuracy: ", metrics.accuracy_score(y_train,neigh.predict(X_train)))
print("Test set accuracy: ", metrics.accuracy_score(y_test,y_pred))